version: '3'

services:
  ibm_server:
    container_name: ibm_server
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/ibm_server
    volumes:
      - ibm_server:/data/ibm_server
    ports:
      - '5432:5432'
    networks:
      - ibm_server_net
    restart: unless-stopped

networks:
  ibm_server_net:
    driver: bridge

volumes:
  ibm_server:
