# Generated by Django 4.1.7 on 2023-05-16 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=100)),
                ('org', models.CharField(max_length=100)),
                ('work_location', models.CharField(max_length=100)),
                ('certifications', models.CharField(max_length=100)),
                ('issue_date', models.DateField()),
                ('type', models.CharField(max_length=100)),
            ],
        ),
    ]
