# Generated by Django 4.1.7 on 2023-05-31 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_control', '0002_alter_certificaciones_issue_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificaciones',
            name='certifications',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='certificaciones',
            name='org',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='certificaciones',
            name='type',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='certificaciones',
            name='uid',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='certificaciones',
            name='work_location',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
